# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ireaver < Formula
  desc "MacOS Photos backup export tool."
  homepage ""
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Celtech/iReaver/releases/1.0.1/iReaver_1.0.1_Darwin_arm64.tar.gz"
      sha256 "fd2b24a7d2eb8b4a1a58dcfc1b129952330c97db45a220334257518e737cee39"

      def install
        bin.install "iReaver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Celtech/iReaver/releases/1.0.1/iReaver_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "c699c259ce3ce431cd769c536a3c7154c33ce710ea674842b1393dee777c8acc"

      def install
        bin.install "iReaver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Celtech/iReaver/releases/1.0.1/iReaver_1.0.1_Linux_x86_64.tar.gz"
      sha256 "2668c98ea042bc17be842917d36d614f8406e46ffa884cb769a9fe68db108503"

      def install
        bin.install "iReaver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Celtech/iReaver/releases/1.0.1/iReaver_1.0.1_Linux_arm64.tar.gz"
      sha256 "ac526bc1e727854704df3492b75e1593fcc1044c3a0ca3c048a2962cf83155f9"

      def install
        bin.install "iReaver"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
