# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ireaver < Formula
  desc "MacOS Photos backup export tool."
  homepage ""
  version "1.0.1"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Celtech/iReaver/releases/download/v1.0.1/iReaver_1.0.1_Darwin_arm64.tar.gz"
      sha256 "6f1d082a3f7e0b83fd6643e107eeed7f58a264a18988fb2731cb3c3c0036e150"

      def install
        bin.install "iReaver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Celtech/iReaver/releases/download/v1.0.1/iReaver_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "b904300f5b8a52ea58ae79e8a839f7dda34bc07079ec99e021d3ad93c60e6cdb"

      def install
        bin.install "iReaver"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
